### ISSUE TITLE
What does is_system_block_ok mean?

### ISSUE THREAD

**Issue by xpe** [for-GET/http-decision-diagram#41]
https://github.com/for-GET/http-decision-diagram/blob/master/doc/README_system.md

**Comment by andreineculau** [comment]
similarly `to is_request_block_ok`, this question can wrap any check that is missed by the diagram.

e.g. if `is_method_allowed` was not in the diagram, but you would need that check, the least you could do is to do that check there, although it would have been rather "late", and you'd have wasted some cpu cycles

Please reopen issue if still not clear.

NOTE: this is in contrast say with how people use webmachine's callbacks: if a check is not done, then you would hijack the `is_authorized` and answer two questions at once. Now that the diagram has a programatic version (Cosmogol + JSON), I think extensibility should be covered by modifying the diagram and thus adjusting the flow to your needs. That said, this check doesn't hurt to be in there by default.
