### ISSUE TITLE
Printer-friendly version

### ISSUE THREAD

**Issue by docksteaderluke** [for-GET/http-decision-diagram#45]
This diagram is **amazing**!

Any chance of arranging it slightly for a more printer-friendly version? It belongs in a frame!

**Comment by andreineculau** [comment]
What are we talking about here? define "more printer-friendly"

You already have https://github.com/for-GET/http-decision-diagram/blob/master/httpdd.png, and ultimately you can also just open http://for-get.github.io/http-decision-diagram/httpdd.fsm.html in a browser and press print. What makes these options not printer-friendly?

Let me know and I'll see what I can do.

**Comment by docksteaderluke** [comment]
I guess what I mean is that you can print it in a **legible** way on standard letter-sized paper (8.5x11). Right now when I print it the text is too small. My first thoughts would be to reduce/remove any excess whitespace and enlarge the label text.

**Comment by andreineculau** [comment]
hmm, good luck with that (printing everything in a legible way on a letter/A4 sized paper) :)

I would gladly look into a PR's changes, if you manage what you want and send a PR. The current state is the balance that I stroke (the first iteration was too bulky, given the number of the FSM datapoints), but obviously improvements could be found that maybe could come close to your goal. I am skeptical that you would reach your goal. Even the ["original"](https://github.com/webmachine/webmachine/blob/master/docs/http-headers-status-v3.png) couldn't be printed on a regular paper in a legible way, thus my skepticism.

**Comment by dmitriid** [comment]
I'd say it's probably possible to print one section per A4 maintaining a bit of legibility. The entire diagram? Doubtful

**Comment by docksteaderluke** [comment]
Hmmm... It was actually pretty close when I first tried to print it. I believe it would be possible to make the necessary modifications. I'll see if I can free up some time to tweak the diagram and submit a PR.

**Comment by andreineculau** [comment]
FWIW I have properly fixed all the calculations of coordinates (was a mess!) and also I've updated a bit the font sizes etc. Maybe it's better/worse now for your goal, but the offer still stands obviously: send a PR, and I'll check it out

**Comment by andreineculau** [comment]
FWIW went a notch further - added a header and export to PNG/JPEG/SVG buttons

**Comment by docksteaderluke** [comment]
Nice!

I'm getting a JavaScript error when running the httpdd.fsm.html file:

```Uncaught TypeError: this.toDataURL is not a function - joint.all.js:36623```

Also, the "Open as PNG" and "Open as SVG" buttons don't seem to do anything. Maybe as a result of the above error? I'm running Chrome 48.0.2564.109 (64-bit) on OSX 10.11.3.

**Comment by andreineculau** [comment]
ignore the error as it doesn't affect the runtime

as for the Open as.. I think chrome was blocking window.open. Should work
now

On Fri, Feb 26, 2016 at 2:35 PM, Luke Docksteader <notifications@github.com>
wrote:

> Nice!
>
> I'm getting a JavaScript error when running the httpdd.fsm.html file:
>
> Uncaught TypeError: this.toDataURL is not a function - joint.all.js:36623
>
> Also, the "Open as PNG" and "Open as SVG" buttons don't seem to do
> anything. Maybe as a result of the above error? I'm running Chrome
> 48.0.2564.109 (64-bit) on OSX 10.11.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/for-GET/http-decision-diagram/issues/45#issuecomment-189276108>
> .
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by docksteaderluke** [comment]
Works now. Thanks!
