### ISSUE TITLE
Configured homepage is 404

### ISSUE THREAD

**Issue by koppor** [for-GET/http-decision-diagram#52]
The configured homepage for this repository is http://hyperrest.github.io/2013-06-10-http-hell-no/:

![grafik](https://user-images.githubusercontent.com/1366654/33367845-31fc1536-d4f0-11e7-9ef3-fe08c660d810.png)

But that leads to

![grafik](https://user-images.githubusercontent.com/1366654/33367881-484d8504-d4f0-11e7-9153-9503025b36e9.png)

Proposal: Enable `gh-pages` for this repository. The content seems to be existing: https://github.com/for-GET/http-decision-diagram/tree/gh-pages

The URL then should be https://for-get.github.io/http-decision-diagram/

**Comment by andreineculau** [comment]
It was a trailing slash. Fixed.
