### ISSUE TITLE
missing_has_precondition

### ISSUE THREAD

**Issue by declaresub** [for-GET/http-decision-diagram#54]
What should missing_has_precondition be checking?  There's no documentation for it yet, and no implementation in for-GET/machine.

**Comment by andreineculau** [comment]
Apologies for the late reply, I probably mark as read the notification email and saw the github notification only now.

This hook should look for a "precondition header" = `If-*` header like `If-Match`. If there is one, since we're on the "resource is missing" branch, we fail early with 412.
