### ISSUE TITLE
201 Created is missing?

### ISSUE THREAD

**Issue by flesler** [for-GET/http-decision-diagram#55]
Where is says `is_process_done -> 202 Accepted`

I think it should split, if the operation could be complemented within the request lifetime it should lead to a `201 Created`, if it accepted for future processing, then yes, `202 Accepted`.

**Comment by flesler** [comment]
I just noticed this is on the top right side, I can't delete the issue :(

**Comment by andreineculau** [comment]
No worries. Let me know if you find other things
