### ISSUE TITLE
Wrong header format?

### ISSUE THREAD

**Issue by KillerBoogie** [for-GET/http-decision-diagram#60]
I miss in this great digram how to deal with wrong formatted headers, e.g. Etag is in incorrect format or Since-Modified is not a correct date.

**Comment by andreineculau** [comment]
Every block has a fallback `is_x_block_ok`. In your case, you want to check if the *request* headers are valid. If invalid, return false on `is_request_block_ok` and return `400 Bad Request`.

Hope it helps.
